### ISSUE TITLE
TH1: Test de firebase 

### ISSUE THREAD

**Issue by VivianaGuerraCustodio** [sumaqkuyay/LIM012-fe-social-network#19]
- [x] Inicio de Sesión

- [x] Registro de usuario.

- [x] Cierre de sesión como usuario activo y registrado.

**Comment by sumaqkuyay** [comment]
@VivianaGuerraCustodio  @Lourdes0896  Realizando la implementación del test para registro , inicio , cerrar sesión , inicio de sesión con facebook y google .

Ver : LIM012-fe-social-network/test/identificator.spec.js

**Comment by sumaqkuyay** [comment]
Las pruebas de Test al 100%
